### ISSUE TITLE
Error in parse(outFile)

### ISSUE THREAD

**Issue by zhengjiji456** [communityecologist/ecopart#1]
Hi, I tried to install this package but met errors.
* installing *source* package ‘ecopart’ ...
** R
Error in parse(outFile) : 
  /private/var/folders/p2/1k88lw1s3xd3tsfbvcv330_00000gn/T/Rtmpvjnixw/R.INSTALLacd296442d9/ecopart/R/ecopart-multi.R:46:30: unexpected '>'
45:     Z       <-  sapply(1:S, function(s) sum(d1[,s]==1 & d2[,s]==1))
46:     Alpha1  <-  rowSums(d1) |>
                                 ^
ERROR: unable to collate and parse R files for package ‘ecopart’

**Comment by communityecologist** [comment]
Thanks Jiji for letting me know about this error. I have now fixed it.

The error stemmed from the fact that I had used "|>" which is a default pipe operator introduced since R 4.1.0.
I have now removed all the "|>" from the source code so that it works on any version of R.

Let me know if any error still appears.

**Comment by zhengjiji456** [comment]
Thanks for your quick response. The package has been installed successfully.
